"""ICD-XS-DM-MCU v0.1 레지스터 주소·코드 정의"""

SLAVE_ADDR = 1

# 보유 레지스터 (DM → MCU)
HB_SEQ = 0x0000
EPOCH_HI = 0x0001
EPOCH_LO = 0x0002
CMD_SEQ = 0x0010
CMD_CODE = 0x0011
CMD_ARG0 = 0x0012
CMD_ARG1 = 0x0013
SET_CLIMATE_MODE = 0x0020
SET_LIGHT = 0x0021
SET_ALARM_OUT = 0x0022
SET_LED_PATTERN = 0x0023
SET_CHG_CURRENT_LIMIT = 0x0024
CFG_COVER_TIMEOUT = 0x0030
CFG_SLIDE_TIMEOUT = 0x0031
CFG_CONTACT_TEMP_MAX = 0x0032
CFG_HB_TIMEOUT = 0x0033

HOLDING_NAMES = {
    HB_SEQ: "HB_SEQ",
    EPOCH_HI: "EPOCH_HI",
    EPOCH_LO: "EPOCH_LO",
    CMD_SEQ: "CMD_SEQ",
    CMD_CODE: "CMD_CODE",
    CMD_ARG0: "CMD_ARG0",
    CMD_ARG1: "CMD_ARG1",
    SET_CLIMATE_MODE: "SET_CLIMATE_MODE",
    SET_LIGHT: "SET_LIGHT",
    SET_ALARM_OUT: "SET_ALARM_OUT",
    SET_LED_PATTERN: "SET_LED_PATTERN",
    SET_CHG_CURRENT_LIMIT: "SET_CHG_CURRENT_LIMIT_10mA",
    CFG_COVER_TIMEOUT: "CFG_COVER_TIMEOUT_100ms",
    CFG_SLIDE_TIMEOUT: "CFG_SLIDE_TIMEOUT_100ms",
    CFG_CONTACT_TEMP_MAX: "CFG_CONTACT_TEMP_MAX_x10",
    CFG_HB_TIMEOUT: "CFG_HB_TIMEOUT_100ms",
}

HOLDING_DEFAULTS = {
    CFG_COVER_TIMEOUT: 300,
    CFG_SLIDE_TIMEOUT: 300,
    CFG_CONTACT_TEMP_MAX: 600,
    CFG_HB_TIMEOUT: 30,
}

# 입력 레지스터 (MCU → DM)
ACK_SEQ = 0x0000
ACK_RESULT = 0x0001
ACK_REASON = 0x0002
DONE_SEQ = 0x0003
DONE_RESULT = 0x0004
DONE_DATA = 0x0005
ACTIVE_SEQ = 0x0006
PROGRESS_PCT = 0x0007
MCU_STATUS = 0x0010
HARD_BLOCK = 0x0011
FAULT_CODE = 0x0012
MCU_TICK = 0x0013
FW_VER_MAJ_MIN = 0x0014
FW_VER_PATCH = 0x0015
UPTIME_HI = 0x0016
UPTIME_LO = 0x0017
COVER_STATE = 0x0020
COVER_LIMITS = 0x0021
COVER_CURRENT = 0x0022
SLIDE_STATE = 0x0023
SLIDE_LIMITS = 0x0024
SLIDE_CURRENT = 0x0025
SLIDE_ENCODER = 0x0026
CHG_STATE = 0x0030
CHG_OUTPUT_ON = 0x0031
CHG_VOLTAGE = 0x0032
CHG_CURRENT = 0x0033
CHG_CURRENT_LIMIT = 0x0034
CONTACT_TEMP = 0x0035
CHG_FAULT_CODE = 0x0036
TEMP_IN = 0x0040
HUM_IN = 0x0041
FLOOD = 0x0042
ENV_STALE = 0x0043
PWR_FLAGS = 0x0050
UPS_VOLTAGE = 0x0051
UPS_SOC = 0x0052
BUS24_V = 0x0053
BUS24_A = 0x0054
BUS48_V = 0x0055
BUS48_A = 0x0056
CLIMATE_MODE = 0x0060
CLIMATE_OUT = 0x0061
LIGHT_STATE = 0x0062
ALARM_OUT_STATE = 0x0063
LED_PATTERN = 0x0064
BMS_LINK = 0x0080
BMS_AGE = 0x0081
BMS_BATTERY_STATUS = 0x0082
BMS_VOLTAGE = 0x0083
BMS_CURRENT_HI = 0x0084
BMS_CURRENT_LO = 0x0085
BMS_RSOC = 0x0086
BMS_REMAIN = 0x0087
BMS_TEMP = 0x0088
BMS_CELL1 = 0x0089
BMS_CYCLE_COUNT = 0x008F
BMS_FAULT_FLAGS_HI = 0x0090
BMS_FAULT_FLAGS_LO = 0x0091
BMS_PWR_STATE = 0x0092
BMS_CHG_FET = 0x0093
BMS_DSG_FET = 0x0094
BMS_CHARGING_CURRENT = 0x0095
BMS_CHARGING_VOLTAGE = 0x0096
BMS_SNAPSHOT_AGE = 0x0097
BMS_TEMP_SHUNT = 0x0098
BMS_TEMP_CELL = 0x0099
BMS_TEMP_FET = 0x009A
BMS_TEMP_INT = 0x009B
BMS_PF_STATUS_HI = 0x009C
BMS_PF_STATUS_LO = 0x009D
BMS_SAFETY_STATUS_HI = 0x009E
BMS_SAFETY_STATUS_LO = 0x009F
BMS_AVG_TIME_TO_FULL = 0x00A0
BMS_CELL_MAX = 0x00A1
BMS_CELL_MIN = 0x00A2
BMS_SERIAL_NUMBER = 0x00B0
BMS_MANUFACTURE_DATE = 0x00B1
BMS_DESIGN_CAPACITY = 0x00B2
BMS_DESIGN_VOLTAGE = 0x00B3
BMS_FULL_CHARGE_CAPACITY = 0x00B4
BMS_DEVICE_TYPE = 0x00B5
BMS_FW_VERSION = 0x00B6
BMS_HW_VERSION = 0x00B7
INPUT_COUNT = 0x00C0

INPUT_NAMES = {
    ACK_SEQ: "ACK_SEQ",
    ACK_RESULT: "ACK_RESULT",
    ACK_REASON: "ACK_REASON",
    DONE_SEQ: "DONE_SEQ",
    DONE_RESULT: "DONE_RESULT",
    DONE_DATA: "DONE_DATA",
    ACTIVE_SEQ: "ACTIVE_SEQ",
    PROGRESS_PCT: "PROGRESS_PCT",
    MCU_STATUS: "MCU_STATUS",
    HARD_BLOCK: "HARD_BLOCK",
    FAULT_CODE: "FAULT_CODE",
    MCU_TICK: "MCU_TICK",
    FW_VER_MAJ_MIN: "FW_VER_MAJ_MIN",
    FW_VER_PATCH: "FW_VER_PATCH",
    UPTIME_HI: "UPTIME_HI",
    UPTIME_LO: "UPTIME_LO",
    COVER_STATE: "COVER_STATE",
    COVER_LIMITS: "COVER_LIMITS",
    COVER_CURRENT: "COVER_CURRENT_mA",
    SLIDE_STATE: "SLIDE_STATE",
    SLIDE_LIMITS: "SLIDE_LIMITS",
    SLIDE_CURRENT: "SLIDE_CURRENT_mA",
    SLIDE_ENCODER: "SLIDE_ENCODER",
    CHG_STATE: "CHG_STATE",
    CHG_OUTPUT_ON: "CHG_OUTPUT_ON",
    CHG_VOLTAGE: "CHG_VOLTAGE_10mV",
    CHG_CURRENT: "CHG_CURRENT_10mA",
    CHG_CURRENT_LIMIT: "CHG_CURRENT_LIMIT_10mA",
    CONTACT_TEMP: "CONTACT_TEMP_x10",
    CHG_FAULT_CODE: "CHG_FAULT_CODE",
    TEMP_IN: "TEMP_IN_x10",
    HUM_IN: "HUM_IN_x10",
    FLOOD: "FLOOD",
    ENV_STALE: "ENV_STALE",
    PWR_FLAGS: "PWR_FLAGS",
    UPS_VOLTAGE: "UPS_VOLTAGE_10mV",
    UPS_SOC: "UPS_SOC_PCT",
    BUS24_V: "BUS24_10mV",
    BUS24_A: "BUS24_10mA",
    BUS48_V: "BUS48_10mV",
    BUS48_A: "BUS48_10mA",
    CLIMATE_MODE: "CLIMATE_MODE",
    CLIMATE_OUT: "CLIMATE_OUT",
    LIGHT_STATE: "LIGHT_STATE",
    ALARM_OUT_STATE: "ALARM_OUT_STATE",
    LED_PATTERN: "LED_PATTERN",
    BMS_LINK: "BMS_LINK",
    BMS_AGE: "BMS_AGE_100ms",
    BMS_BATTERY_STATUS: "BMS_BATTERY_STATUS",
    BMS_VOLTAGE: "BMS_VOLTAGE_mV",
    BMS_CURRENT_HI: "BMS_CURRENT_mA_HI",
    BMS_CURRENT_LO: "BMS_CURRENT_mA_LO",
    BMS_RSOC: "BMS_RSOC_PCT",
    BMS_REMAIN: "BMS_REMAIN_mAh",
    BMS_TEMP: "BMS_TEMP_0p1K",
    BMS_CELL1 + 0: "BMS_CELL1_mV",
    BMS_CELL1 + 1: "BMS_CELL2_mV",
    BMS_CELL1 + 2: "BMS_CELL3_mV",
    BMS_CELL1 + 3: "BMS_CELL4_mV",
    BMS_CELL1 + 4: "BMS_CELL5_mV",
    BMS_CELL1 + 5: "BMS_CELL6_mV",
    BMS_CYCLE_COUNT: "BMS_CYCLE_COUNT",
    BMS_FAULT_FLAGS_HI: "BMS_FAULT_FLAGS_HI",
    BMS_FAULT_FLAGS_LO: "BMS_FAULT_FLAGS_LO",
    BMS_PWR_STATE: "BMS_PWR_STATE",
    BMS_CHG_FET: "BMS_CHG_FET",
    BMS_DSG_FET: "BMS_DSG_FET",
    BMS_CHARGING_CURRENT: "BMS_CHARGING_CURRENT_mA",
    BMS_CHARGING_VOLTAGE: "BMS_CHARGING_VOLTAGE_mV",
    BMS_SNAPSHOT_AGE: "BMS_SNAPSHOT_AGE_ms",
    BMS_TEMP_SHUNT: "BMS_TEMP_SHUNT_x10",
    BMS_TEMP_CELL: "BMS_TEMP_CELL_x10",
    BMS_TEMP_FET: "BMS_TEMP_FET_x10",
    BMS_TEMP_INT: "BMS_TEMP_INT_x10",
    BMS_PF_STATUS_HI: "BMS_PF_STATUS_HI",
    BMS_PF_STATUS_LO: "BMS_PF_STATUS_LO",
    BMS_SAFETY_STATUS_HI: "BMS_SAFETY_STATUS_HI",
    BMS_SAFETY_STATUS_LO: "BMS_SAFETY_STATUS_LO",
    BMS_AVG_TIME_TO_FULL: "BMS_AVG_TIME_TO_FULL_min",
    BMS_CELL_MAX: "BMS_CELL_MAX_mV",
    BMS_CELL_MIN: "BMS_CELL_MIN_mV",
    BMS_SERIAL_NUMBER: "BMS_SERIAL_NUMBER",
    BMS_MANUFACTURE_DATE: "BMS_MANUFACTURE_DATE",
    BMS_DESIGN_CAPACITY: "BMS_DESIGN_CAPACITY_mAh",
    BMS_DESIGN_VOLTAGE: "BMS_DESIGN_VOLTAGE_mV",
    BMS_FULL_CHARGE_CAPACITY: "BMS_FULL_CHARGE_CAPACITY_mAh",
    BMS_DEVICE_TYPE: "BMS_DEVICE_TYPE",
    BMS_FW_VERSION: "BMS_FW_VERSION",
    BMS_HW_VERSION: "BMS_HW_VERSION",
}

SIGNED_INPUTS = (SLIDE_ENCODER, CONTACT_TEMP, TEMP_IN, BMS_TEMP_SHUNT, BMS_TEMP_CELL, BMS_TEMP_FET, BMS_TEMP_INT)

# 폴링 블록 (시작, 워드 수)
STATUS_BLOCK = (0x0000, 112)
BMS_BLOCK = (0x0080, 48)
BMS_IDENT_BLOCK = (0x00B0, 16)

# 명령 코드
COVER_OPEN = 0x0001
COVER_CLOSE = 0x0002
SLIDE_EXTEND = 0x0003
SLIDE_RETRACT = 0x0004
CHARGE_ON = 0x0005
CHARGE_OFF = 0x0006
BMS_POWER_ON = 0x0007
BMS_POWER_OFF = 0x0008
MOTION_STOP = 0x0009
CLEAR_HOLD = 0x000A
CLEAR_FAULT = 0x000B
BMS_READ_WORD = 0x000C
BMS_WRITE_WORD = 0x000D
MCU_RESET = 0x000E
STATION_POWER_CYCLE = 0x000F

CMD_NAMES = {
    COVER_OPEN: "COVER_OPEN",
    COVER_CLOSE: "COVER_CLOSE",
    SLIDE_EXTEND: "SLIDE_EXTEND",
    SLIDE_RETRACT: "SLIDE_RETRACT",
    CHARGE_ON: "CHARGE_ON",
    CHARGE_OFF: "CHARGE_OFF",
    BMS_POWER_ON: "BMS_POWER_ON",
    BMS_POWER_OFF: "BMS_POWER_OFF",
    MOTION_STOP: "MOTION_STOP",
    CLEAR_HOLD: "CLEAR_HOLD",
    CLEAR_FAULT: "CLEAR_FAULT",
    BMS_READ_WORD: "BMS_READ_WORD",
    BMS_WRITE_WORD: "BMS_WRITE_WORD",
    MCU_RESET: "MCU_RESET",
    STATION_POWER_CYCLE: "STATION_POWER_CYCLE",
}

MOTION_CMDS = (COVER_OPEN, COVER_CLOSE, SLIDE_EXTEND, SLIDE_RETRACT)
BMS_CMDS = (BMS_POWER_ON, BMS_POWER_OFF, BMS_READ_WORD, BMS_WRITE_WORD)
CMD_HI_REJECT = {
    COVER_OPEN: (4, 6),
    COVER_CLOSE: (1, 4, 6),
    SLIDE_EXTEND: (2, 3, 4, 6),
    SLIDE_RETRACT: (4, 6),
    CHARGE_ON: (5, 6),
}
BMS_WRITE_ALLOWED = (0x00, 0x01, 0x02, 0x03, 0x04, 0x80)
MCU_RESET_MAGIC = 0x5A5A
POWER_CYCLE_MAGIC = 0xA5A5
POWER_CYCLE_DEFAULT_DELAY_S = 10

# 거부·폴트 코드
OK = 0x0000
HI1 = 0x0001
HI2 = 0x0002
HI3 = 0x0003
HI4 = 0x0004
HI5 = 0x0005
HI6 = 0x0006
BUSY = 0x0010
SAFE_HOLD = 0x0011
FAULT_LATCHED = 0x0012
BMS_NO_LINK = 0x0013
BMS_REJECT = 0x0014
CONTACT_OVERTEMP = 0x0015
BAD_ARG = 0x0016
UNKNOWN_CMD = 0x0017
NO_AC = 0x0018
MOTION_TIMEOUT = 0x0020
LIMIT_CONFLICT = 0x0021

REASON_NAMES = {
    OK: "OK",
    HI1: "HI-1",
    HI2: "HI-2",
    HI3: "HI-3",
    HI4: "HI-4",
    HI5: "HI-5",
    HI6: "HI-6",
    BUSY: "BUSY",
    SAFE_HOLD: "SAFE_HOLD",
    FAULT_LATCHED: "FAULT_LATCHED",
    BMS_NO_LINK: "BMS_NO_LINK",
    BMS_REJECT: "BMS_REJECT",
    CONTACT_OVERTEMP: "CONTACT_OVERTEMP",
    BAD_ARG: "BAD_ARG",
    UNKNOWN_CMD: "UNKNOWN_CMD",
    NO_AC: "NO_AC",
    MOTION_TIMEOUT: "MOTION_TIMEOUT",
    LIMIT_CONFLICT: "LIMIT_CONFLICT",
}

# 상태 값 이름
DONE_RESULT_NAMES = {0: "OK", 1: "TIMEOUT", 2: "ABORTED", 3: "HW_ERROR", 4: "INTERLOCK"}
COVER_STATE_NAMES = {0: "closed", 1: "opening", 2: "open", 3: "closing", 4: "unknown"}
SLIDE_STATE_NAMES = {0: "retracted", 1: "extending", 2: "extended", 3: "retracting", 4: "unknown"}
CHG_STATE_NAMES = {0: "off", 1: "on", 2: "fault"}
CHG_FAULT_NAMES = {0: "none", 1: "contact_overtemp", 2: "overcurrent", 3: "no_current", 4: "bms_reject"}
LED_PATTERN_NAMES = {
    0: "OFF", 1: "대기", 2: "모션 중", 3: "개방 대기", 4: "드론 비행 중",
    5: "SAFE-HOLD", 6: "FAULT", 7: "정비 모드", 8: "충전 중", 9: "업데이트 중",
}
MCU_STATUS_BITS = ("estop", "safe_hold", "fault", "hb_timeout", "sd_ok", "bms_link", "drone_detected", "motion_active")
HARD_BLOCK_BITS = ("HI-1", "HI-2", "HI-3", "HI-4", "HI-5", "HI-6")
COVER_LIMIT_BITS = ("front_closed", "front_open", "side_closed", "side_open", "front_door", "side_door")
SLIDE_LIMIT_BITS = ("home", "extended")
CLIMATE_OUT_BITS = ("heater", "cooler", "fan")
LIGHT_BITS = ("inner", "outer")
ALARM_BITS = ("buzzer", "indicator")
PWR_FLAG_BITS = ("ac_ok", "ups_on_battery", "ups_charging")
ENV_STALE_BITS = ("temp_hum", "flood")
